#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# Clear cache.
rm $HOME/.cache/dunst.log

# Set wallpaper
feh --bg-fill ~/Pictures/wallpapers/arch.png &

polybar main -r &
dunst --config $HOME/.config/dunst/dunstrc &
picom --experimental-backends --backend glx &

#start network
nmcli dev wifi connect Dejanira password PASSWORD &

# I hate mouse drift.
xset m 0 0
xsetroot -cursor_name left_ptr

# Set keyboard abnt2 
setxkbmap -model abnt2 -layout br 

# Start MPD and mpDris2
exec mpd &
exec mpDris2 &

# Active NumLock
numlockx on &

# Bspwm configs

bspc monitor -d 1 2 3 4 5 6 7 8 9
rule Viewnior                       state=floating
rule Pavucontrol                    state=floating
rule Thunar                         state=floating

bspc config active_border_color   "#16161e"
bspc config normal_border_color  "#16161e"
bspc config focused_border_color  "#F8F8F2"
bspc config presel_feedback_color "#BD93F9"

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio               0.50
bspc config gapless_monocle           true
bspc config single_monocle            true
bspc config focus_follows_pointer     true
bspc config remove_unplugged_monitors true
bspc config borderless_monocle   true
bspc config gapless_monocle      true


